/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.trackviewer.postgres.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.trackviewer.postgres.tables.DayReport;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DayReportRecord extends UpdatableRecordImpl<DayReportRecord> implements Record5<Integer, Integer, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = -6407163;

    /**
     * Setter for <code>public.day_report.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.day_report.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.day_report.total_waiting</code>.
     */
    public void setTotalWaiting(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.day_report.total_waiting</code>.
     */
    public Integer getTotalWaiting() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.day_report.distance</code>.
     */
    public void setDistance(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.day_report.distance</code>.
     */
    public Integer getDistance() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.day_report.ts</code>.
     */
    public void setTs(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.day_report.ts</code>.
     */
    public Timestamp getTs() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.day_report.vehicle_number</code>.
     */
    public void setVehicleNumber(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.day_report.vehicle_number</code>.
     */
    public Integer getVehicleNumber() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DayReport.DAY_REPORT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DayReport.DAY_REPORT.TOTAL_WAITING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DayReport.DAY_REPORT.DISTANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DayReport.DAY_REPORT.TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DayReport.DAY_REPORT.VEHICLE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTotalWaiting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDistance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getVehicleNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTotalWaiting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDistance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getVehicleNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DayReportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DayReportRecord value2(Integer value) {
        setTotalWaiting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DayReportRecord value3(Integer value) {
        setDistance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DayReportRecord value4(Timestamp value) {
        setTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DayReportRecord value5(Integer value) {
        setVehicleNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DayReportRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DayReportRecord
     */
    public DayReportRecord() {
        super(DayReport.DAY_REPORT);
    }

    /**
     * Create a detached, initialised DayReportRecord
     */
    public DayReportRecord(Integer id, Integer totalWaiting, Integer distance, Timestamp ts, Integer vehicleNumber) {
        super(DayReport.DAY_REPORT);

        set(0, id);
        set(1, totalWaiting);
        set(2, distance);
        set(3, ts);
        set(4, vehicleNumber);
    }
}
