/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.trackviewer.postgres.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.trackviewer.postgres.tables.WaitPoints;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaitPointsRecord extends UpdatableRecordImpl<WaitPointsRecord> implements Record6<Timestamp, BigDecimal, BigDecimal, Integer, Integer, Long> {

    private static final long serialVersionUID = 425058023;

    /**
     * Setter for <code>public.wait_points.ts</code>.
     */
    public void setTs(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.wait_points.ts</code>.
     */
    public Timestamp getTs() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.wait_points.lng</code>.
     */
    public void setLng(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.wait_points.lng</code>.
     */
    public BigDecimal getLng() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.wait_points.lat</code>.
     */
    public void setLat(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.wait_points.lat</code>.
     */
    public BigDecimal getLat() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.wait_points.waiting</code>.
     */
    public void setWaiting(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.wait_points.waiting</code>.
     */
    public Integer getWaiting() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.wait_points.waitpoints_id</code>.
     */
    public void setWaitpointsId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.wait_points.waitpoints_id</code>.
     */
    public Integer getWaitpointsId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.wait_points.id</code>.
     */
    public void setId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.wait_points.id</code>.
     */
    public Long getId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Timestamp, BigDecimal, BigDecimal, Integer, Integer, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Timestamp, BigDecimal, BigDecimal, Integer, Integer, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return WaitPoints.WAIT_POINTS.TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return WaitPoints.WAIT_POINTS.LNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return WaitPoints.WAIT_POINTS.LAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return WaitPoints.WAIT_POINTS.WAITING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return WaitPoints.WAIT_POINTS.WAITPOINTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return WaitPoints.WAIT_POINTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getLng();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getWaiting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getWaitpointsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getLng();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWaiting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getWaitpointsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord value1(Timestamp value) {
        setTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord value2(BigDecimal value) {
        setLng(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord value3(BigDecimal value) {
        setLat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord value4(Integer value) {
        setWaiting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord value5(Integer value) {
        setWaitpointsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord value6(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaitPointsRecord values(Timestamp value1, BigDecimal value2, BigDecimal value3, Integer value4, Integer value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaitPointsRecord
     */
    public WaitPointsRecord() {
        super(WaitPoints.WAIT_POINTS);
    }

    /**
     * Create a detached, initialised WaitPointsRecord
     */
    public WaitPointsRecord(Timestamp ts, BigDecimal lng, BigDecimal lat, Integer waiting, Integer waitpointsId, Long id) {
        super(WaitPoints.WAIT_POINTS);

        set(0, ts);
        set(1, lng);
        set(2, lat);
        set(3, waiting);
        set(4, waitpointsId);
        set(5, id);
    }
}
