/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.trackviewer.postgres.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.trackviewer.postgres.Indexes;
import ru.smartsarov.trackviewer.postgres.Keys;
import ru.smartsarov.trackviewer.postgres.Public;
import ru.smartsarov.trackviewer.postgres.tables.records.VehicleDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleData extends TableImpl<VehicleDataRecord> {

    private static final long serialVersionUID = 818095598;

    /**
     * The reference instance of <code>public.vehicle_data</code>
     */
    public static final VehicleData VEHICLE_DATA = new VehicleData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehicleDataRecord> getRecordType() {
        return VehicleDataRecord.class;
    }

    /**
     * The column <code>public.vehicle_data.id</code>.
     */
    public final TableField<VehicleDataRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('vehicle_dat_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.vehicle_data.uid</code>.
     */
    public final TableField<VehicleDataRecord, String> UID = createField("uid", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.vehicle_data.number</code>.
     */
    public final TableField<VehicleDataRecord, String> NUMBER = createField("number", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.vehicle_data.type</code>.
     */
    public final TableField<VehicleDataRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.vehicle_data</code> table reference
     */
    public VehicleData() {
        this(DSL.name("vehicle_data"), null);
    }

    /**
     * Create an aliased <code>public.vehicle_data</code> table reference
     */
    public VehicleData(String alias) {
        this(DSL.name(alias), VEHICLE_DATA);
    }

    /**
     * Create an aliased <code>public.vehicle_data</code> table reference
     */
    public VehicleData(Name alias) {
        this(alias, VEHICLE_DATA);
    }

    private VehicleData(Name alias, Table<VehicleDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private VehicleData(Name alias, Table<VehicleDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> VehicleData(Table<O> child, ForeignKey<O, VehicleDataRecord> key) {
        super(child, key, VEHICLE_DATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VEHICLE_DAT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VehicleDataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VEHICLE_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VehicleDataRecord> getPrimaryKey() {
        return Keys.VEHICLE_DAT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VehicleDataRecord>> getKeys() {
        return Arrays.<UniqueKey<VehicleDataRecord>>asList(Keys.VEHICLE_DAT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehicleData as(String alias) {
        return new VehicleData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehicleData as(Name alias) {
        return new VehicleData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleData rename(String name) {
        return new VehicleData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleData rename(Name name) {
        return new VehicleData(name, null);
    }
}
