/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.trackviewer.postgres;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.smartsarov.trackviewer.postgres.tables.HourReport;
import ru.smartsarov.trackviewer.postgres.tables.RegionRb;
import ru.smartsarov.trackviewer.postgres.tables.TrackingData;
import ru.smartsarov.trackviewer.postgres.tables.VehicleData;
import ru.smartsarov.trackviewer.postgres.tables.WaitPoints;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1084212413;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.hour_report</code>.
     */
    public final HourReport HOUR_REPORT = ru.smartsarov.trackviewer.postgres.tables.HourReport.HOUR_REPORT;

    /**
     * The table <code>public.region_rb</code>.
     */
    public final RegionRb REGION_RB = ru.smartsarov.trackviewer.postgres.tables.RegionRb.REGION_RB;

    /**
     * The table <code>public.tracking_data</code>.
     */
    public final TrackingData TRACKING_DATA = ru.smartsarov.trackviewer.postgres.tables.TrackingData.TRACKING_DATA;

    /**
     * The table <code>public.vehicle_data</code>.
     */
    public final VehicleData VEHICLE_DATA = ru.smartsarov.trackviewer.postgres.tables.VehicleData.VEHICLE_DATA;

    /**
     * The table <code>public.wait_points</code>.
     */
    public final WaitPoints WAIT_POINTS = ru.smartsarov.trackviewer.postgres.tables.WaitPoints.WAIT_POINTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HOUR_REPORT_ID_SEQ,
            Sequences.REGION_RB_ID_SEQ,
            Sequences.TRACKING_DATA_ID_SEQ,
            Sequences.VEHICLE_DAT_ID_SEQ,
            Sequences.WAIT_POINTS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            HourReport.HOUR_REPORT,
            RegionRb.REGION_RB,
            TrackingData.TRACKING_DATA,
            VehicleData.VEHICLE_DATA,
            WaitPoints.WAIT_POINTS);
    }
}
